type: object
properties: 
  id: 
    type: string
    format: uuid
    description: The unique identifier of the image
  url:
    type: string
    format: url
    description: The url of the image
    minLength: 5
    maxLength: 500
    nullable: true
    example: https://raw.githubusercontent.com/ecristobale/apifirst-spring-boot/refs/heads/main/DDD%20design/Entidad%20Customer%20Programacion%20con%20Value%20Objects%20y%20objetos.png
  altText:
    type: [string, 'null']
    minLength: 3
    maxLength: 255
    nullable: true
required:
  - id