openapi: 3.0.4
info:
  version: 1.0.0
  title: API First with Spring Boot 
  termsOfService: https://example.com/terms/
  contact:
    email: edu_ce_1988@hotmail.com
    url: https://github.com/ecristobale
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://avatars.githubusercontent.com/u/29001205?v=4
  description: |-
    This is a **example** to demonstrate features of OpenAPI 3.0 specification.
tags:
  - name: User
    description: Operations about user
#   - name: Echo
#     description: Everything about your user
#   - name: Tag
#     description: this is a tag description
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://example.com/api/v1
paths:
  /users/{username}:
    $ref: paths/users_{username}.yml
  # /echo:
  #   $ref: paths/echo.yaml
  # /pathItem:
  #   $ref: paths/pathItem.yaml
  # /pathItemWithExamples:
  #   $ref: paths/pathItemWithExamples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic