get:
  tags:
    - Product
  summary: Get a product by ID
  description: |
    Get a product by ID.
  operationId: getProductById
  parameters:
    - $ref: ../../components/parameters/product_id.yaml
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product.yaml
    '400':
      description: Bad Request
    '404':
      description: Not Found
put:
  tags:
    - Product
  summary: Update a product by ID
  description: |
    Update a product by ID.
  operationId: updateProductById
  parameters:
    - $ref: ../../components/parameters/product_id.yaml
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/v1/product_update.yaml
  responses:
    '200':
      description: Product Updated
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product.yaml
    '400':
      description: Bad Request 
    '404':
      description: Not Found
patch:
  tags:
    - Product
  summary: Patch a product by ID
  description: |
    Patch a product by ID.
  operationId: patchProductById
  parameters:
    - $ref: ../../components/parameters/product_id.yaml
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/v1/product_patch.yaml
  responses:
    '200':
      description: Product Patched
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product.yaml
    '400':
      description: Bad Request 
    '404':
      description: Not Found
delete:
  tags:
    - Product
  summary: Delete a product by ID
  description: |
    Delete a product by ID.
  operationId: deleteProductById
  parameters:
    - $ref: ../../components/parameters/product_id.yaml
  responses:
    '204':
      description: No Content
    '400':
      description: Bad Request 
    '404':
      description: Not Found
    '409':
      description: Conflict